server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: template-service
          uri: lb://template-service
          predicates:
          - Path=/template/**
          filters:
          - RewritePath=/template/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: message-service
          uri: lb://message-service
          predicates:
          - Path=/message/**
          filters:
          - RewritePath=/message/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie


keycloak:
    auth-server-url: http://localhost:8080/auth
    bearer-only: true
    credentials:
        secret: 5988f899-a5bf-4f76-b15f-f1cd0d2c81ba
    realm: spmia-realm
    resource: saas
    ssl-required: external
    use-resource-role-mappings: true    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        